apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: promtail-token
  annotations:
    kubernetes.io/service-account.name: promtail
type: kubernetes.io/service-account-token
