apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: minecraft-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 31000
