apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
      - name: vscode
        image: codercom/code-server
        env:
        - name: PASSWORD
          value: "ChangeThisPassword"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vscode-service
spec:
  type: ClusterIP
  selector:
    app: vscode
  ports:
    - port: 8080
      targetPort: 8080
